#!/bin/sh
 
start() {
  net_addr=`cat /crypi/data/networking_addr.dat`
  net_mask=`cat /crypi/data/networking_mask.dat`
  net_gw=`cat /crypi/data/networking_gateway.dat`
  sudo /sbin/ifconfig eth0 $net_addr netmask $net_mask
  sudo /sbin/route add default gw $net_gw
}
 
stop() {
  echo "Nothing to do here..."
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    //stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
