#!/bin/sh
### BEGIN INIT INFO
# Provides:          crypi_ramdisk
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Sets IPv4 addresses like configured in CryPi settings
### END INIT INFO
 
start() {
  mount -t tmpfs -o size=15M none /crypi/upload_tmp
  mount -t tmpfs -o size=50M none /crypi/upload_workdir
  chown www-data:www-data /crypi/upload_tmp
  chown www-data:www-data /crypi/upload_workdir
}
 
stop() {
  umount /crypi/upload_tmp
  umount /crypi/upload_workdir/
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac
